spec/ttml-ww-profiles.html

Resolves #85

---

spec/xml-schemas/imsc1-all.xsd

Resolves #86
- adds an imsc-all.xsd that imports all necessary namespaces and provides pointers to XSD files

Addresses #86

---

spec/ttml-ww-profiles.html

Resolves #94 as suggested at https://github.com/w3c/imsc/issues/94#issue-118079968

Addresses #94

---

spec/ttml-ww-profiles.html

Addresses #96

---

spec/ttml-ww-profiles.html

Addresses Issue 97

---

spec/ttml-ww-profiles.html

Ambiguous recommendation on line height usage

---

spec/ttml-ww-profiles.html

Constraint on text outline is ambiguous.

---

spec/ttml-ww-profiles.html

Confirm list of scripts for which Gcpy = 12 (issue #103)

---

spec/ttml-ww-profiles.html

Constraint on extent should apply to both profiles (Issue #101)

---

spec/ttml-ww-profiles.html

Need to specify whether #backgroundColor* is permitted in image profile (#112)

---

spec/ttml-ww-profiles.html

Resolves #115
Resolves #116 
Resolves #117

Ambiguous feature dispositions (#115, #116 and #117)

---

spec/ttml-ww-profiles.html

Constrains the number of div elements in Image Profile (#118)

---

spec/ttml-ww-profiles.html

Old process reference

---

spec/ttml-ww-profiles.html

Addresses #134 ("SDP-US document may not adhere to HRM")

---

spec/substantive-changes-summary.txt
spec/ttml-ww-profiles.html

Addresses #136 ("Documents that have no content may be conformant to both profiles")

---

spec/substantive-changes-summary.txt
spec/ttml-ww-profiles.html

Address #146 (redundant 'boundary' term)

---

test/w3c/linePadding/linePadding1.ttml
test/w3c/multiRowAlign/multiRowAlign1.ttml

Address #167 (Fix lineHeight in EBU-TT-D examples)

---

spec/ttml-ww-profiles.html

Address #114 (Definition of prohibited does not prohibit presence of feature)

---

spec/ttml-ww-profiles.html

Address #150 (tts:fontFamily recommendations)

---

spec/ttml-ww-profiles.html

Addresses #127 (Extensibility goals not documented)

---

imsc1/spec/ttml-ww-profiles.html

Added a note that #zIndex is not used

---

imsc1/spec/ttml-ww-profiles.html

Recommend begin+dur in addition to begin+end

---

imsc1/spec/examples/activeArea-example.xml
imsc1/spec/examples/editorialArea-example.xml
imsc1/spec/ttml-ww-profiles.html

Add support for editorial area

---

imsc1/spec/examples/altText-example.xml
imsc1/spec/ttml-ww-profiles.html

Fixes typo in altText example

---

imsc1/spec/ttml-ww-profiles.html
imsc1/spec/xml-schemas/imsc1-parameters.xsd
imsc1/spec/xml-schemas/imsc1-styling.xsd

Update XSDs and clarify parameter syntax

---

imsc1/spec/ttml-ww-profiles.html

Clarify requirement that regions are contained within root container

---

imsc1/spec/ttml-ww-profiles.html

Discourage the use of tab characters in <p> and <span>

---

imsc1/spec/ttml-ww-profiles.html

Moved SDP-US to bibliographic reference
Closes #246

Clarified signaling of simultaneous conformance with SDP-US and EBU-TT-D

---

imsc1/spec/ttml-ww-profiles.html

Fixes incorrect namespace prefixes

---

imsc1/spec/ttml-ww-profiles.html

Clarify extent units

---

imsc1/spec/ttml-ww-profiles.html

Clarify relationship with imsc1.0.1

---

imsc1/spec/ttml-ww-profiles.html

Close #3 
Close #124 
Close #125

Updated profile signaling and resolution to match TTML2 semantics

---

imsc1/spec/ttml-ww-profiles.html

Deprecates #writingMode-horizontal-rl in Image Profile

---

imsc1/spec/ttml-ww-profiles.html

Deprecate #progressivelyDecodable

---

imsc1/spec/ttml-ww-profiles.html

Clarify forcedDisplay semantics

---

imsc1/spec/ttml-ww-profiles.html

White space cleanup. Will merge tomorrow.

Tidy specification

---

imsc1/spec/examples/forcedDisplay-example.xml
imsc1/spec/examples/text-example.xml
imsc1/spec/ttml-ww-profiles.html

Deprecate ittp:aspectRatio

---

imsc1/spec/ttml-ww-profiles.html

Remove nested ruby and ruby overhang features

---

imsc1/spec/ttml-ww-profiles.html

Remove background-color feature per removal in TTML2

---

imsc1/spec/examples/activeArea-example.xml
imsc1/spec/examples/fillLineGap-example.xml
imsc1/spec/examples/forcedDisplay-example.xml
imsc1/spec/examples/image-example.xml
imsc1/spec/examples/text-and-smptett-example.xml
imsc1/spec/examples/text-example.xml
imsc1/spec/ttml-ww-profiles.html

Remove ttp:version and fix examples

---

imsc1/spec/ttml-ww-profiles.html

Add permitted-deprecated link to Section 6

---

imsc1/spec/ttml-ww-profiles.html

Clarify the limits of Active Area per its syntax

---

imsc1/spec/ttml-ww-profiles.html

Close #213 
See https://github.com/w3c/imsc/issues/213#issuecomment-356486553

Clarify handling of foreign elements and attributes

---

imsc1/spec/ttml-ww-profiles.html

Use Root Container Region consistently

---

imsc1/spec/ttml-ww-profiles.html

Clarify style resolution procedure

---

imsc1/spec/ttml-ww-profiles.html

Change process to 2018 process

---

imsc1/spec/ttml-ww-profiles.html

Update scope per deprecation model

---

imsc1/spec/ttml-ww-profiles.html

Remove recommendations on time expressions and ttp:cellResolution

---

imsc1/spec/manifest.txt
imsc1/spec/substantive-changes-summary.txt
imsc1/spec/ttml-ww-profiles.html

Matches https://github.com/w3c/imsc/releases/tag/imsc1.0.1-PR-20180227

IMSC1.0.1-PR

---

imsc1/spec/ttml-ww-profiles.html

Fixed typo in color example

---

imsc1/spec/examples/image-example.xml

Modify image profile example to use TTML <image>

---

imsc1/spec/ttml-ww-profiles.html

Clarify relationship with SMPTE-TT

---

imsc1/spec/ttml-ww-profiles.html

Remove recommendation against TAB characters per TTML2 semantics

---

imsc1/spec/examples/imsc1-image-example.xml
imsc1/spec/examples/text-and-ebuttd-example.xml
imsc1/spec/examples/text-and-smptett-example.xml
imsc1/spec/ttml-ww-profiles.html

Close #331
Built at https://rawgit.com/w3c/imsc/issue-331-refactor-profile-signaling/imsc1/spec/ttml-ww-profiles.html
Diff at https://services.w3.org/htmldiff?doc1=https%3A%2F%2Frawgit.com%2Fw3c%2Fimsc%2FIMSC1.1%2Fimsc1%2Fspec%2Fttml-ww-profiles.html&doc2=https%3A%2F%2Frawgit.com%2Fw3c%2Fimsc%2Fissue-331-refactor-profile-signaling%2Fimsc1%2Fspec%2Fttml-ww-profiles.html

Refactor profile signaling provisions

---

imsc1/spec/ttml-ww-profiles.html

Close #341
Created using https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2Fttml2&doc2=https%3A%2F%2Fw3c.github.io%2Fttml2%2Findex.html#feature-textEmphasis
Built at https://rawgit.com/w3c/imsc/issue-341-update-TTML2-feature-list/imsc1/spec/ttml-ww-profiles.html

Update feature list per TTML2

---

imsc1/spec/ttml-ww-profiles.html

Editorial tweaks

---

imsc1/spec/ttml-ww-profiles.html

Add explanatory text on profiles and processors

---

imsc1/spec/ttml-ww-profiles.html

Closes #316 
_Please use `-w` when diffing_

Point reader to Media Accessibility User Requirements

---

imsc1/spec/ttml-ww-profiles.html

Fix merge errors at f72ca9867704dcef1650bf93ffe0cbb603c2c50c

---

imsc1/spec/ttml-ww-profiles.html

Change document license back to W3C document license

---

imsc1/spec/ttml-ww-profiles.html

Document license set to W3C document license per WG resolution

---

imsc1/spec/substantive-changes-summary.txt
imsc1/spec/ttml-ww-profiles.html

_DO NOT MERGE_
Prepare IMSC 1.1 for CR

IMSC 1.1 CR1

---

imsc1/spec/ttml-ww-profiles.html

Improve accessibility of table colors

---

imsc1/spec/ttml-ww-profiles.html

Add support for negative values (#370, #394)
Clarify support for #textOrientation-sideways-LR (#373)
Added #extent-length (#382)
Move tts:position constraints to Text Profile (#392)
Fix localBiblio bug
Refactor feature lists per TTML2 CR2 (#390, #393)
Replace `tts:fontShear` with `tts:shear` and `tts:lineShear` (#401)

Refactor features tables

---

imsc1/spec/ttml-ww-profiles.html

Apply workaround to <img> resize issue

---

imsc1/spec/ttml-ww-profiles.html

Relax <annotation-position> constraints

---

imsc1/spec/ttml-ww-profiles.html

Add tts:textShadow to HRM glyph definition

---

imsc1/spec/ttml-ww-profiles.html

Limit number of tts:textShadow <values> to 4

---

imsc1/spec/ttml-ww-profiles.html

Add support for tts:rubyAlign='spaceAround'

---

imsc1/spec/ttml-ww-profiles.html

Improve description of dependent features and links to feature definitions

---

imsc1/spec/ttml-ww-profiles.html

Refactor tts:origin constraint

---

imsc1/spec/ttml-ww-profiles.html

Clarify the recommendation on tts:lineHeight='normal'

---

imsc1/spec/ttml-ww-profiles.html

Also update the URLs for EBU-TT-M and EBU-TT-D.
Closes #427 and #428.

Move definition of conformsToStandard to EBU-TT-M

---

imsc1/spec/ttml-ww-profiles.html

Permit multiRowAlign and linePadding on initial

---

imsc1/spec/ttml-ww-profiles.html

Explicitly prohibit tt:image when smpte:backgroundImage is present

---

imsc1/spec/substantive-changes-summary.txt
imsc1/spec/ttml-ww-profiles.html

IMSC 1.1 CR2

---

imsc1/spec/ttml-ww-profiles.html

Move master branch to Editor's Draft

Move to ED

---

imsc1/spec/ttml-ww-profiles.html

 Informative section headers made consistent

---

imsc1/spec/ttml-ww-profiles.html

 Add Stefan Poeschel to the acknowledgements

---

imsc1/spec/ttml-ww-profiles.html

Fix color contrast

---

imsc1/spec/ttml-ww-profiles.html

 Clean reference shortcut text

---

imsc1/spec/substantive-changes-summary.txt
imsc1/spec/ttml-ww-profiles.html

Constrain rh/rw on tts:extent and tts:position

---

imsc1/spec/ttml-ww-profiles.html

Add image element to note at §5.1

---

imsc1/spec/substantive-changes-summary.txt
imsc1/spec/ttml-ww-profiles.html

Remove tts:lineShear

---

imsc1/spec/ttml-ww-profiles.html

Remove duplicate conformance text

---

imsc1/spec/ttml-ww-profiles.html

Remove tts:lineShear from note at Section 8.4.5

---

imsc1/spec/ttml-ww-profiles.html

Clean-up Annex L and apply Tidy

---

imsc1/spec/ttml-ww-profiles.html

DO NOT MERGE UNTIL PUBLISHED
Built at https://rawgit.com/w3c/imsc/release/imsc1.1-PR/imsc1/spec/ttml-ww-profiles.html
Addresses #455

IMSC 1.1 Draft Proposed Recommendation

---

.pr-preview.json

Add automatic PR diff generation

---

imsc1/spec/manifest.txt
imsc1/spec/substantive-changes-summary.txt
imsc1/spec/ttml-ww-profiles.html

_DO NOT MERGE UNTIL PUBLICATION_
References in informative sections were changed to informative references per respec.

IMSC 1.1 Recommendation

---

imsc1/spec/ttml-ww-profiles.html

Close #475 
Close #469
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/pull/482.html" title="Last updated on Jul 19, 2019, 9:54 AM UTC (537cde9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/482/82d9ab0...537cde9.html" title="Last updated on Jul 19, 2019, 9:54 AM UTC (537cde9)">Diff</a>

Loosen and clarify tts:extent constraints

---

imsc1/spec/ttml-ww-profiles.html

Close #486
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/pull/487.html" title="Last updated on Sep 1, 2019, 8:48 PM UTC (d8ade28)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/487/880376f...d8ade28.html" title="Last updated on Sep 1, 2019, 8:48 PM UTC (d8ade28)">Diff</a>

Clarify #position and #origin constraints

---

imsc1/spec/ttml-ww-profiles.html

Closes #472
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/pull/485.html" title="Last updated on Oct 4, 2019, 5:49 PM UTC (873b9e6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/485/ff03b7a...873b9e6.html" title="Last updated on Oct 4, 2019, 5:49 PM UTC (873b9e6)">Diff</a>

Add support for #font

---

imsc1/spec/ttml-ww-profiles.html

Closes #488
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/pull/501.html" title="Last updated on Oct 29, 2019, 3:20 PM UTC (b0c4ede)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/501/a17746f...b0c4ede.html" title="Last updated on Oct 29, 2019, 3:20 PM UTC (b0c4ede)">Diff</a>

Clarify partially supported disposition

---

imsc1/spec/ttml-ww-profiles.html

Closes #503
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/pull/504.html" title="Last updated on Oct 30, 2019, 10:07 AM UTC (f836c0b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/504/d335896...f836c0b.html" title="Last updated on Oct 30, 2019, 10:07 AM UTC (f836c0b)">Diff</a>

Update security and privacy considerations

---

imsc1/spec/Overview.html
imsc1/spec/ttml-ww-profiles.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/pull/496.html" title="Last updated on Dec 4, 2019, 5:01 AM UTC (2b69176)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/496/12e2f46...2b69176.html" title="Last updated on Dec 4, 2019, 5:01 AM UTC (2b69176)">Diff</a>

IMSC 1.2 FPWD

---

imsc1/spec/examples/fillLineGap-example-2.xml
imsc1/spec/ttml-ww-profiles.html

Closes #505
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/pull/507.html" title="Last updated on Dec 5, 2019, 3:08 PM UTC (d940112)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/507/bc6be60...d940112.html" title="Last updated on Dec 5, 2019, 3:08 PM UTC (d940112)">Diff</a>

Correct profile signaling in examples

---

imsc1/spec/ttml-ww-profiles.html

Closes #506
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/pull/518.html" title="Last updated on Jan 30, 2020, 4:33 PM UTC (5eb6299)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/518/83f8f61...5eb6299.html" title="Last updated on Jan 30, 2020, 4:33 PM UTC (5eb6299)">Diff</a>

Clarify use of validation tools to warn about overly constrained uses of content and processor profile

---

imsc1/spec/ttml-ww-profiles.html

Related to #530
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/pull/532.html" title="Last updated on Mar 23, 2020, 3:12 PM UTC (99e7d68)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/532/8c3ad69...99e7d68.html" title="Last updated on Mar 23, 2020, 3:12 PM UTC (99e7d68)">Diff</a>

Reference the CSS discussion related to font-based fingerprinting attacks and mitigation strategies

---

imsc1/spec/ttml-ww-profiles.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/pull/534.html" title="Last updated on Mar 27, 2020, 8:54 PM UTC (ece15fa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/534/4b72015...ece15fa.html" title="Last updated on Mar 27, 2020, 8:54 PM UTC (ece15fa)">Diff</a>

Update per CR publication

---

imsc1/spec/ttml-ww-profiles.html

Closes #531
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/pull/536.html" title="Last updated on Apr 10, 2020, 3:43 PM UTC (28b37a7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/536/6d9c7d7...28b37a7.html" title="Last updated on Apr 10, 2020, 3:43 PM UTC (28b37a7)">Diff</a>

Update TTML2 ref to point to TTML2 2ED

---

imsc1/spec/ttml-ww-profiles.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/pull/535.html" title="Last updated on Apr 10, 2020, 3:44 PM UTC (aa8dc27)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/535/d8ef8d6...aa8dc27.html" title="Last updated on Apr 10, 2020, 3:44 PM UTC (aa8dc27)">Diff</a>

Use https scheme for resource URLs in examples

---

imsc1/spec/ttml-ww-profiles.html

Closing #521
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/pull/542.html" title="Last updated on Apr 23, 2020, 3:19 PM UTC (5fc5790)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/542/fd20895...5fc5790.html" title="Last updated on Apr 23, 2020, 3:19 PM UTC (5fc5790)">Diff</a>

Improve note regarding the use of altText for content authors

---

imsc1/spec/ttml-ww-profiles.html

Closes #523
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/pull/527.html" title="Last updated on May 13, 2020, 7:33 PM UTC (7e33286)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/527/f6ecbeb...7e33286.html" title="Last updated on May 13, 2020, 7:33 PM UTC (7e33286)">Diff</a>
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/pull/527.html" title="Last updated on May 14, 2020, 9:22 AM UTC (3e427a4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/527/f6ecbeb...3e427a4.html" title="Last updated on May 14, 2020, 9:22 AM UTC (3e427a4)">Diff</a>

Note that the user can influence the document processing context

---

imsc1/spec/ttml-ww-profiles.html

Closes #519 and #520
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/pull/526.html" title="Last updated on May 14, 2020, 5:30 PM UTC (2e3298f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/526/46949b7...2e3298f.html" title="Last updated on May 14, 2020, 5:30 PM UTC (2e3298f)">Diff</a>

Address A11Y comments related to WCAG 2.1

---

imsc1/spec/ttml-ww-profiles.html

fix for 1.2 (current WD)
***
<a href="https://pr-preview.s3.amazonaws.com/himorin/imsc/pull/541.html" title="Last updated on May 29, 2020, 5:34 PM UTC (e8167e2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/541/18dbed5...himorin:e8167e2.html" title="Last updated on May 29, 2020, 5:34 PM UTC (e8167e2)">Diff</a>

updated latest IMSC recommendation link

---

imsc1/spec/ttml-ww-profiles.html

This PR is not for immediate release, but to be used on future release by edited or amended recommendation (not in-place edits).
***
<a href="https://pr-preview.s3.amazonaws.com/himorin/imsc/pull/540.html" title="Last updated on Jun 1, 2020, 6:10 AM UTC (d15e91f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/540/6a0bdfe...himorin:d15e91f.html" title="Last updated on Jun 1, 2020, 6:10 AM UTC (d15e91f)">Diff</a>

replaced link to imsc REC, not for release but for future use

---

imsc1/spec/ttml-ww-profiles.html

changed two links to https://github.com/liberationfonts/liberation-fonts

---

imsc1/spec/ttml-ww-profiles.html

*DO NOT MERGE*
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/pull/554.html" title="Last updated on May 29, 2020, 5:38 PM UTC (f3e7c87)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/554/18dbed5...f3e7c87.html" title="Last updated on May 29, 2020, 5:38 PM UTC (f3e7c87)">Diff</a>

WIP: IMSC 1.2 Proposed Recommendation

---

imsc1/spec/ttml-ww-profiles.html

(just in case if this is needed...)
***
<a href="https://pr-preview.s3.amazonaws.com/himorin/imsc/pull/565.html" title="Last updated on Aug 6, 2020, 3:16 PM UTC (508ecb0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/565/4cf38c2...himorin:508ecb0.html" title="Last updated on Aug 6, 2020, 3:16 PM UTC (508ecb0)">Diff</a>

HTML to HTML/images.html

---

imsc1/spec/ttml-ww-profiles.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/pull/564.html" title="Last updated on Aug 6, 2020, 3:20 PM UTC (388709a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/564/4cf38c2...388709a.html" title="Last updated on Aug 6, 2020, 3:20 PM UTC (388709a)">Diff</a>

WIP: IMSC 1.2 Recommendation

---

imsc1/spec/ttml-ww-profiles.html

per comment https://github.com/w3c/imsc/commit/1744c5ce99d25511592f6a184665ff56483df92a#r42615145
***
<a href="https://pr-preview.s3.amazonaws.com/himorin/imsc/pull/567.html" title="Last updated on Jan 7, 2021, 7:09 AM UTC (6b918e1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/567/1744c5c...himorin:6b918e1.html" title="Last updated on Jan 7, 2021, 7:09 AM UTC (6b918e1)">Diff</a>

updated respec group configuration

---

imsc1/spec/ttml-ww-profiles.html

https://github.com/w3c/imsc/issues/544

Add JA character set

---

imsc1/spec/ttml-ww-profiles.html

Remove obsolete note regarding forcedDisplay applicability

---

.pr-preview.json
imsc1/spec/ttml-ww-profiles.html

- switched async to defer, per [pr-preview known issues](https://github.com/tobie/pr-preview#known-issues)
- added params.force to .pr-preview.json

potential fix for pr-preview issue
