w3c/imsc

spec/ttml-ww-profiles.html
Resolves #68 
- removed the terms "complex" and "simple" script
- refactored GCpy, Ren and NGBS table
- move "Simple Scripts" table into GCpy, Ren and NGBS table
=> Addresses https://github.com/w3c/imsc/issues/68#issuecomment-156165035

spec/ttml-ww-profiles.html
Resolves #84 
- added Note to ittp:aspectRatio section
- clarified "Related Video Object frame" to "image frame of the Related Video Object"
=> Addresses #84

spec/ttml-ww-profiles.html
Resolves #81 
Recommends `ttp:cellResolution` on \<tt\> if `c` is used in the Document
=> Addresses #81

spec/ttml-ww-profiles.html
=> Add note indicating line padding can only use 'c' units (#110) 

spec/ttml-ww-profiles.html
=> Nested span feature prohibition is redundant in image profile (#113)

spec/ttml-ww-profiles.html
Closes #128
Reverts the prohibition on `ttp:profile` introduced by #79
=> Address #128 (Compatibility with SDP-US)

testsuite/linePadding/linePadding1.ttml, testsuite/multiRowAlign/multiRowAlign1.ttml
The test suites samples for line padding and multirow align have been drafted to be compatible with EBU-TT-D. They were not any more due to the addition of the ttp:profile attribute in PR #140. Therefore the indication of the profiles should be done as proposed in the spec using the ebuttm:conformsToStandard element.
Closes #148
=> Addresses #148 (Change profile signalling in files with ebu-tt-d extensions)

spec/examples/image-example.xml, spec/examples/text-and-ebuttd-example.xml, spec/examples/text-and-smptett-example.xml, spec/examples/text-example.xml, spec/ttml-ww-profiles.html
* Change EBU-TT-D encoding statement to remove specific reference to
UTF-16 and mention EBU-TT-D recommendation for UTF-8.
* Make EBU-TT-D example validate against EBU-TT-D schema by moving
`tts:lineHeight` specification from `<body>` to `"baseStyle" <style>`.
* Fix typo of supplemented
* Tighten up wording re SMPTE-TT constraints and remove redundant
bullet.
=> Address line comments for issue-126 branch made by @nigelmegitt

spec/ttml-ww-profiles.html
=> Addresses #111 ("Need algorithm to determine profile in absence of ttp:profile property")

spec/ttml-imsc1-errata.html
removed names from 1st paragraph. Added John in s 2nd paragraph. Added a wording on DECE.
=> removed names 

ttml-imsc-versions.html
Per [TTWG Meeting 2016-04-14](https://www.w3.org/2016/04/14-tt-minutes.html), this PR proposes a IMSC roadmap document to be hosted at http://www.w3.org/TR/ttml-imsc-versions/.
As discussed, this would allow each published revision of IMSC to point to both:
- the most recent revision of this version of IMSC (through the usual "Latest version" link)
- a list of all versions of IMSC (through a link to the roadmap document)
=> Add IMSC roadmap document

imsc1/spec/examples/activeArea-example.xml, imsc1/spec/ttml-ww-profiles.html
Closes #211.
* Change `ittp:activeArea` to use `leftOffset topOffset` for position
instead of `x y`.
* Add requirement that the percentage values are not greater than 100%.
* Reference CSS3 backgrounds and borders informatively.
* Provide an informative method for deriving the x and y coordinates of
the top left of the active area.
* Modify example.
=> Fix #211 by changing x y to leftOffset topOffset

imsc1/misc/tidy.cfg, imsc1/spec/ttml-ww-profiles.html
Fix #219.
* Reference TTML and XML security
* Mention that XML Entity Expansion is prohibited
* Include slightly edited version of the draft Privacy of Preference
section from WebVTT (credit @dwsinger and @zcorpan) which also applies
here.
* Include Security and Privacy related to Images..
=> Add Security and Privacy section

imsc1/spec/examples/fillLineGap-example.xml, imsc1/spec/examples/text-and-ebuttd-example.xml, imsc1/spec/examples/text-and-smptett-example.xml
=> Remove tabs from examples (issue #225)

imsc1/spec/ttml-ww-profiles.html
=> Required spaces between non-terminal components of styling and parameter attributes (issue #221)

imsc1/spec/ttml-ww-profiles.html
=> Deprecate ittm:altText

imsc1/spec/ttml-ww-profiles.html
=> Prohibit simultaneous tts:origin and tts:position

imsc1/spec/ttml-ww-profiles.html
=> Defer to TTML2 for security and privacy considerations 

imsc1/spec/ttml-ww-profiles.html
=> Clarify name of IMSC namespaces

imsc1/spec/ttml-ww-profiles.html
=> Prohibit usesForced metadata item

imsc1/spec/ttml-ww-profiles.html
Proposal to change the EBU-TT-D conformance section to define signalling of conformance to the profiles defined in this specification and refer to IMSC 1.0.1 for how to signal conformance to a profile in that specification, while also including the information informatively as an assistance to the reader.
=> Specify only EBU-TT-D conformance to this spec

imsc1/spec/ttml-ww-profiles.html
Reformat features table (#363)
Add link to constraints in features table (#359)
Fix #background disposition (#374)
Misc editorial fixes (#375)
Add deprecation warning to ittp:progressivelyDecodable (#376)
Add link to constraints in features table (#380)
=> Miscellaneous editorial fixes

imsc1/spec/ttml-ww-profiles.html
=> Address draft CR2 comments

imsc1/spec/ttml-ww-profiles.html
=> Clarify that the concrete encoding uses XML 1.0

.pr-preview.json
Specify the path to the spec file rather than leaving as the default index.html, which does not correspond to a file in the repo.
=> Attempt to make PR preview work

imsc1/spec/ttml-ww-profiles.html
Closes #516 :
* State that processors may use CSS 3 font matching algorithm.
* State that fonts may be mapped to font resources using the `@font-face` rule.
* Tabulate mapping of `font` element attributes and child element attributes to CSS descriptors
* Note the potential discrepancy between line height computation font selection and rendering font selection.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/pull/517.html" title="Last updated on Feb 13, 2020, 4:03 PM UTC (349ed01)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/517/53faae4...349ed01.html" title="Last updated on Feb 13, 2020, 4:03 PM UTC (349ed01)">Diff</a>
=> Permit CSS font matching and font-face mapping

imsc1/spec/ttml-ww-profiles.html
#522
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/pull/552.html" title="Last updated on Jun 2, 2020, 3:58 PM UTC (43c5672)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/552/afdee37...43c5672.html" title="Last updated on Jun 2, 2020, 3:58 PM UTC (43c5672)">Diff</a>
=> Added introduction

imsc1/spec/ttml-ww-profiles.html
Updated with dates fixed.
ref. https://w3c.github.io/spec-releases/milestones/?pr=2020-06-16
=> updated prEnd and publishDate to final one

imsc1/spec/substantive-changes-summary.txt, imsc1/spec/ttml-ww-profiles.html
Closes #560 
Closes #561
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/pull/562.html" title="Last updated on Jul 16, 2020, 1:36 PM UTC (102d3d7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/562/beea041...102d3d7.html" title="Last updated on Jul 16, 2020, 1:36 PM UTC (102d3d7)">Diff</a>
=> Clarified links to EBU specifications and other miscellaneous edits

imsc1/spec/ttml-ww-profiles.html
(for future use)
From [recent respec update](https://lists.w3.org/Archives/Public/spec-prod/2020JulSep/0002.html), replace 'wg', 'wgURI', 'wgPatentURI' with 'group': 
> ## `group` configuration option
> 
> With a new configuration option — “group”, you can specify a “shortname” for the WG/CG and let ReSpec figure out the details for you. The wg, wgId, wgURI, and wgPatentURI options are deprecated in favour of “group”.
'timed-text' is from [list](https://respec.org/w3c/groups/)
***
<a href="https://pr-preview.s3.amazonaws.com/himorin/imsc/pull/563.html" title="Last updated on Aug 6, 2020, 3:29 PM UTC (0ff0ca6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/563/fd1ca89...himorin:0ff0ca6.html" title="Last updated on Aug 6, 2020, 3:29 PM UTC (0ff0ca6)">Diff</a>
=> use 'group' instead of 'wg', 'wgURI', 'wgPatentURI'

imsc1/spec/ttml-ww-profiles.html
updated with 'document'
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Feb 7, 2023, 4:27 AM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fimsc%2Ff7833ff814693c70111061b7ad05a9c4a51ccc85%2Fimsc1%2Fspec%2Fttml-ww-profiles.html%3FisPreview%3Dtrue)
_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, …
=> fix license config of respec

imsc1/spec/ttml-ww-profiles.html
=> Add JA character set

imsc1/spec/ttml-ww-profiles.html
=> Refactor the HRM

imsc1/spec/ttml-ww-profiles.html
=> Bump WCAG 2.1 to WCAG 2.2

imsc1/spec/ttml-ww-profiles.html
=> Remove Image Profile
